# version: '3.8'

# services:
#   app:
#     build: .
#     depends_on:
#       - redis
#     environment:
#       REDIS_HOST: redis  
#     ports:
#       - "5000:5000"  
#   redis:
#     image: redis:latest  
#     container_name: redis-server
#     ports:
#       - "6379:6379"  # Expose Redis port (6379) to the host machine
